# Generated by Django 5.2 on 2025-04-30 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, verbose_name='Nombre')),
                ('city', models.CharField(blank=True, max_length=250, verbose_name='Ciudad')),
                ('postal_code', models.IntegerField(blank=True, verbose_name='Postal')),
                ('address', models.CharField(blank=True, max_length=250, verbose_name='Direccion')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('phone', models.IntegerField(blank=True, verbose_name='Telefono')),
            ],
        ),
    ]
