# Generated by Django 5.2 on 2025-05-17 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school', '0001_initial'),
        ('team', '0002_remove_team_dg'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_team_score', models.IntegerField(blank=True, null=True)),
                ('away_team_score', models.IntegerField(blank=True, null=True)),
                ('date', models.DateTimeField()),
                ('status', models.CharField(choices=[('PROGRAMADO', 'Programado'), ('CURSO', 'En curso'), ('FINALIZADO', 'Finalizado'), ('POSPUESTO', 'Pospuesto'), ('CANCELADO', 'Cancelado')], default='PROGRAMADO', max_length=30)),
                ('referee', models.CharField(blank=True, max_length=200, null=True)),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_visitor', to='team.team')),
                ('local_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_local', to='team.team')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school', to='school.school')),
            ],
        ),
    ]
