# Generated by Django 5.2.1 on 2025-06-05 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0003_alter_match_away_team_score_and_more'),
        ('player', '0003_alter_player_equipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerMatchStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat_type', models.CharField(choices=[('GOL', 'Gol'), ('ASISTENCIA', 'Asistencia'), ('ROJA', 'Roja'), ('AMARILLA', 'Amarilla'), ('RESULTADO', 'Resultado')], max_length=50)),
                ('value', models.IntegerField()),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_stats', to='match.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_stats', to='player.player')),
            ],
            options={
                'unique_together': {('match', 'player', 'stat_type')},
            },
        ),
    ]
