# Generated by Django 5.2 on 2025-05-03 14:51

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True
    dependencies = [
    ]
    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('edad', models.IntegerField(default=0)),
                ('posicion', models.CharField(choices=[('PORT', 'Portero'), ('DEF', 'Defensa'), ('MED', 'Centrocampista'), ('DEL', 'Delantero')], max_length=5)),
                ('dorsal', models.IntegerField(default=0)),
                ('goles', models.IntegerField(default=0)),
                ('asistencias', models.IntegerField(default=0)),
                ('faltas', models.IntegerField(default=0)),
                ('amarillas', models.IntegerField(default=0)),
                ('rojas', models.IntegerField(default=0)),
                ('minutos_jugados', models.IntegerField(default=0)),
                ('partidos_jugados', models.IntegerField(default=0)),
            ],
        ),
    ]
