# Generated by Django 5.2 on 2025-05-03 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0002_initial'),
        ('team', '0002_remove_team_dg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='equipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jugadores', to='team.team'),
        ),
    ]
