# Generated by Django 5.2 on 2025-05-17 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_experience'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='level',
        ),
    ]
