# Generated by Django 5.2 on 2025-05-26 15:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('match', '0002_match_result'),
        ('player', '0003_alter_player_equipo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApuestaUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CondicionApuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('match', 'Partido'), ('player', 'Jugador')], max_length=50)),
                ('predicted_result', models.CharField(blank=True, max_length=10, null=True)),
                ('stat_type', models.CharField(choices=[('GOL', 'Gol'), ('ASISTENCIA', 'Asistencia'), ('ROJA', 'Roja'), ('AMARILLA', 'Amarilla')], max_length=50)),
                ('predicted_value', models.IntegerField(blank=True, null=True)),
                ('apuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='apuestaUsuario.apuestausuario')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='match.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player.player')),
            ],
        ),
    ]
