# Generated by Django 5.2 on 2025-05-26 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apuestaUsuario', '0001_initial'),
        ('player', '0003_alter_player_equipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condicionapuesta',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='player.player'),
        ),
        migrations.AlterField(
            model_name='condicionapuesta',
            name='stat_type',
            field=models.CharField(choices=[('GOL', 'Gol'), ('ASISTENCIA', 'Asistencia'), ('ROJA', 'Roja'), ('AMARILLA', 'Amarilla'), ('RESULTADO', 'Resultado')], max_length=50),
        ),
    ]
