# Generated by Django 5.2 on 2025-05-27 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apuestaUsuario', '0002_alter_condicionapuesta_player_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='condicionapuesta',
            name='is_winner',
            field=models.BooleanField(default=False),
        ),
    ]
