# Generated by Django 5.2 on 2025-05-27 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apuestaUsuario', '0003_condicionapuesta_is_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='condicionapuesta',
            name='settled',
            field=models.BooleanField(default=False),
        ),
    ]
