# Generated by Django 5.2 on 2025-05-27 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apuestaUsuario', '0004_condicionapuesta_settled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='condicionapuesta',
            name='settled',
        ),
        migrations.AddField(
            model_name='apuestausuario',
            name='settled',
            field=models.BooleanField(default=False),
        ),
    ]
